build:
  stage: build
  tags:
    - dev
  image: maven:3.9-eclipse-temurin-21
  script:
    - mvn clean package -DskipTests
    - mv target/*.jar target/todo-$CI_COMMIT_SHORT_SHA.jar
  artifacts:
    paths:
      - target/todo-$CI_COMMIT_SHORT_SHA.jar
  cache:
    paths:
      - .m2/repository